spring:
  application:
    name: text-book-illustration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false


server:
  port: ${SERVER_PORT}

app:
  file-storage-root: ${FILE_STORAGE_ROOT}
  step-timeout-seconds: ${STEP_TIMEOUT_SECONDS}
  max-retry-count: ${MAX_RETRY_COUNT}
  cors-allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  gemini:
    api-key: ${GEMINI_API_KEY}
    base-url: https://generativelanguage.googleapis.com/v1beta
    api-revision: "2026-05-20"
    text-model: ${APP_GEMINI_TEXT_MODEL}